sonar.projectKey=Goldbursch_static-code-analysis
sonar.organization=goldbursch

# Display name in the SonarCloud UI
sonar.projectName=static-code-analysis

# Path to source files relative to the sonar-project.properties file
sonar.sources=.

# Encoding of source files
sonar.sourceEncoding=UTF-8
